services:
#  bot:
#    build: .
#    container_name: soccer_assistant_bot
#    depends_on:
#      - db
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/soccer_assistant_bot
#      - TG_BOT_TOKEN=7722206304:AAEp4Y-CA_f1BfrxsuckVWIudbXufzJYp5Q
#    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soccer_assistant_bot
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

volumes:
  postgres_data:
