name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-deploy
        chmod 600 ~/.ssh/github-deploy
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/github-deploy ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          cd ~/soccer-bot || git clone https://github.com/NikitaKorneev/tg_soccer_assistant.git ~/soccer-bot && cd ~/soccer-bot
          git pull origin main
          docker compose down
          docker compose up -d --build
        EOF
